In [1]:
import numpy as np

In [5]:
# Graded cell
def center_data(Y):
    """
    Center your original data
    Args:
         Y (ndarray): input data. Shape (n_observations x n_pixels)
    Outputs:
        X (ndarray): centered data
    """
    ### START CODE HERE ###
    mean_vector = np.mean(Y, axis=0)
    print("Mean vector", mean_vector)
    print("--------------------")
    mean_matrix = np.repeat(mean_vector, Y.shape[0])
    print("Mean matrix", mean_matrix)
    print("--------------------")
    # use np.reshape to reshape into a matrix with the same size as Y. Remember to use order='F'
    mean_matrix = np.reshape(mean_matrix, Y.shape, order='F')
    print("Mean matrix reshaped", mean_matrix)
    
    X = Y - mean_matrix
    ### END CODE HERE ###
    return X

In [6]:
A1 = np.array([[1, 2, 3], 
               [4, 5, 6],
               [7, 8, 9]])
center_data(A1.transpose())

Mean vector [4. 5. 6.]
--------------------
Mean matrix [4. 4. 4. 5. 5. 5. 6. 6. 6.]
--------------------
Mean matrix reshaped [[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


array([[-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.]])